version: "3.4"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    command: npm start
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge